### ISSUE TITLE
Not kicking after banning

### ISSUE THREAD

**Issue by BigJazzz** [RedstoneDubstep/Tempban#1]
Running 1.19 version, and banning works, however I need to then kick the player after as it's not forcing a disconnect. When they try to reconnect it tells them they're banned.

**Comment by RedstoneDubstep** [comment]
Hello, are you using Fabric or Forge? And what version of Tempban are you using?

**Comment by BigJazzz** [comment]
Hey, my apologies for forgetting that info.

We're using the Forge version, but I've just realised that what I stupidly thought was the mod version in the title is actually the MC version. I've currently got 1.20 installed, but we're running a 1.19.2 server. I'll download the correct MC version and see if that works. I'll let you know how we go.

**Comment by BigJazzz** [comment]
Ok, turns out using the correct version is workign as intended. Sorry for the confusion.
